# Site settings
title: Hardware Livre USP
header-img: img/header06.jpg
email: harduime@googlegroups.com
copyright_name: Hardware Livre USP
description: ""
baseurl: ""
url: "http://hardwarelivreusp.org"
github_username:  HardwareLivreUSP
facebook_username:  Hardwarelivreusp
# email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
paginate_path: "/blog/page:num/"
exclude: ["node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

sass:
  style: compressed
